version: "3.8"

services:
  nginx:
    image: nginx:1.21.0
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  db:
    platform: linux/x86_64
    container_name: meshi_db
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - 4306:3306
  api:
    container_name: meshi_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: "air"
    env_file: ./docker.env
    volumes:
      - .:/meshi-api
      - bin:/meshi-api/bin
    ports:
      - 8080
volumes:
  bin:
