FROM golang:1.16.5-alpine3.14

RUN apk --update --no-cache add git build-base openssh curl nmap mysql-client tzdata bash ca-certificates jq && \
  update-ca-certificates

ENV TZ Asia/Tokyo

COPY install.sh ./
RUN cat install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /meshi-api

COPY go.mod go.sum /meshi-api/
RUN go mod download

COPY . /meshi-api

RUN chmod 755 ./entry-point.sh
ENTRYPOINT [ "./entry-point.sh" ]
