version: "3.8"

services:
  nginx:
    restart: always
    image: nginx:1.21.0
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  db:
    restart: always
    container_name: meshi_db
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - 4306:3306
  api:
    restart: always
    container_name: meshi_api
    image: bamboooo/meshi-api
    entrypoint: "./bin/meshi-api"
    ports:
      - 8080:8080
    depends_on:
      - db
