version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 4306:3306
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: "air"
    volumes:
      - .:/meshi-api
      - bin:/bin/meshi-api
    ports:
      - 8080
volumes:
  bin:
