// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Like struct {
	UserID       string `json:"userId"`
	RestaurantID string `json:"restaurantId"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
