// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LikesColumns holds the columns for the "likes" table.
	LikesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "restaurant_likes", Type: field.TypeString, Nullable: true},
	}
	// LikesTable holds the schema information for the "likes" table.
	LikesTable = &schema.Table{
		Name:       "likes",
		Columns:    LikesColumns,
		PrimaryKey: []*schema.Column{LikesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "likes_restaurants_likes",
				Columns:    []*schema.Column{LikesColumns[2]},
				RefColumns: []*schema.Column{RestaurantsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "like_user_id_restaurant_likes",
				Unique:  true,
				Columns: []*schema.Column{LikesColumns[1], LikesColumns[2]},
			},
		},
	}
	// RestaurantsColumns holds the columns for the "restaurants" table.
	RestaurantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
		{Name: "price", Type: field.TypeString},
	}
	// RestaurantsTable holds the schema information for the "restaurants" table.
	RestaurantsTable = &schema.Table{
		Name:       "restaurants",
		Columns:    RestaurantsColumns,
		PrimaryKey: []*schema.Column{RestaurantsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LikesTable,
		RestaurantsTable,
	}
)

func init() {
	LikesTable.ForeignKeys[0].RefTable = RestaurantsTable
}
