// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RestaurantsColumns holds the columns for the "restaurants" table.
	RestaurantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
		{Name: "price", Type: field.TypeString},
	}
	// RestaurantsTable holds the schema information for the "restaurants" table.
	RestaurantsTable = &schema.Table{
		Name:        "restaurants",
		Columns:     RestaurantsColumns,
		PrimaryKey:  []*schema.Column{RestaurantsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RestaurantsTable,
	}
)

func init() {
}
