// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/bamboooo-dev/meshi-api/ent/migrate"

	"github.com/bamboooo-dev/meshi-api/ent/restaurant"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Restaurant is the client for interacting with the Restaurant builders.
	Restaurant *RestaurantClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Restaurant = NewRestaurantClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Restaurant: NewRestaurantClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:     cfg,
		Restaurant: NewRestaurantClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Restaurant.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Restaurant.Use(hooks...)
}

// RestaurantClient is a client for the Restaurant schema.
type RestaurantClient struct {
	config
}

// NewRestaurantClient returns a client for the Restaurant from the given config.
func NewRestaurantClient(c config) *RestaurantClient {
	return &RestaurantClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `restaurant.Hooks(f(g(h())))`.
func (c *RestaurantClient) Use(hooks ...Hook) {
	c.hooks.Restaurant = append(c.hooks.Restaurant, hooks...)
}

// Create returns a create builder for Restaurant.
func (c *RestaurantClient) Create() *RestaurantCreate {
	mutation := newRestaurantMutation(c.config, OpCreate)
	return &RestaurantCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Restaurant entities.
func (c *RestaurantClient) CreateBulk(builders ...*RestaurantCreate) *RestaurantCreateBulk {
	return &RestaurantCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Restaurant.
func (c *RestaurantClient) Update() *RestaurantUpdate {
	mutation := newRestaurantMutation(c.config, OpUpdate)
	return &RestaurantUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RestaurantClient) UpdateOne(r *Restaurant) *RestaurantUpdateOne {
	mutation := newRestaurantMutation(c.config, OpUpdateOne, withRestaurant(r))
	return &RestaurantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RestaurantClient) UpdateOneID(id int) *RestaurantUpdateOne {
	mutation := newRestaurantMutation(c.config, OpUpdateOne, withRestaurantID(id))
	return &RestaurantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Restaurant.
func (c *RestaurantClient) Delete() *RestaurantDelete {
	mutation := newRestaurantMutation(c.config, OpDelete)
	return &RestaurantDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RestaurantClient) DeleteOne(r *Restaurant) *RestaurantDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RestaurantClient) DeleteOneID(id int) *RestaurantDeleteOne {
	builder := c.Delete().Where(restaurant.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RestaurantDeleteOne{builder}
}

// Query returns a query builder for Restaurant.
func (c *RestaurantClient) Query() *RestaurantQuery {
	return &RestaurantQuery{
		config: c.config,
	}
}

// Get returns a Restaurant entity by its id.
func (c *RestaurantClient) Get(ctx context.Context, id int) (*Restaurant, error) {
	return c.Query().Where(restaurant.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RestaurantClient) GetX(ctx context.Context, id int) *Restaurant {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RestaurantClient) Hooks() []Hook {
	return c.hooks.Restaurant
}
