// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (l *Like) Restaurant(ctx context.Context) (*Restaurant, error) {
	result, err := l.Edges.RestaurantOrErr()
	if IsNotLoaded(err) {
		result, err = l.QueryRestaurant().Only(ctx)
	}
	return result, err
}

func (r *Restaurant) Likes(ctx context.Context) ([]*Like, error) {
	result, err := r.Edges.LikesOrErr()
	if IsNotLoaded(err) {
		result, err = r.QueryLikes().All(ctx)
	}
	return result, err
}
