// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/bamboooo-dev/meshi-api/ent/like"
	"github.com/bamboooo-dev/meshi-api/ent/restaurant"
)

// Like is the model entity for the Like schema.
type Like struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LikeQuery when eager-loading is set.
	Edges            LikeEdges `json:"edges"`
	restaurant_likes *string
}

// LikeEdges holds the relations/edges for other nodes in the graph.
type LikeEdges struct {
	// Restaurant holds the value of the restaurant edge.
	Restaurant *Restaurant `json:"restaurant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RestaurantOrErr returns the Restaurant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LikeEdges) RestaurantOrErr() (*Restaurant, error) {
	if e.loadedTypes[0] {
		if e.Restaurant == nil {
			// The edge restaurant was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: restaurant.Label}
		}
		return e.Restaurant, nil
	}
	return nil, &NotLoadedError{edge: "restaurant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Like) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case like.FieldID, like.FieldUserID:
			values[i] = new(sql.NullString)
		case like.ForeignKeys[0]: // restaurant_likes
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Like", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Like fields.
func (l *Like) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case like.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				l.ID = value.String
			}
		case like.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				l.UserID = value.String
			}
		case like.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field restaurant_likes", values[i])
			} else if value.Valid {
				l.restaurant_likes = new(string)
				*l.restaurant_likes = value.String
			}
		}
	}
	return nil
}

// QueryRestaurant queries the "restaurant" edge of the Like entity.
func (l *Like) QueryRestaurant() *RestaurantQuery {
	return (&LikeClient{config: l.config}).QueryRestaurant(l)
}

// Update returns a builder for updating this Like.
// Note that you need to call Like.Unwrap() before calling this method if this Like
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Like) Update() *LikeUpdateOne {
	return (&LikeClient{config: l.config}).UpdateOne(l)
}

// Unwrap unwraps the Like entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Like) Unwrap() *Like {
	tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Like is not a transactional entity")
	}
	l.config.driver = tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Like) String() string {
	var builder strings.Builder
	builder.WriteString("Like(")
	builder.WriteString(fmt.Sprintf("id=%v", l.ID))
	builder.WriteString(", user_id=")
	builder.WriteString(l.UserID)
	builder.WriteByte(')')
	return builder.String()
}

// Likes is a parsable slice of Like.
type Likes []*Like

func (l Likes) config(cfg config) {
	for _i := range l {
		l[_i].config = cfg
	}
}
