// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/bamboooo-dev/meshi-api/ent/restaurant"
	"github.com/bamboooo-dev/meshi-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	restaurantFields := schema.Restaurant{}.Fields()
	_ = restaurantFields
	// restaurantDescName is the schema descriptor for name field.
	restaurantDescName := restaurantFields[0].Descriptor()
	// restaurant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	restaurant.NameValidator = restaurantDescName.Validators[0].(func(string) error)
}
