name: build-and-deploy

on:
  push:
    branches:
      - main
      - yamagai/modify-cd

jobs:
  build-image:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Set commit hash
        run: echo "::set-output name=COMMIT_HASH::${GITHUB_SHA}"
        id: set-commit-hash

      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ORG_YAMAGAI_DOCKER_USER }}
          password: ${{ secrets.ORG_YAMAGAI_DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            bamboooo/meshi-api:${{ steps.set-commit-hash.outputs.COMMIT_HASH }}

  deploy:
    needs: build-image

    name: Deploy to cluster
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to roots
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.ORG_ROOTS_KUBE_CONFIG }}
          version: v1.21.2
          command: set image --record deployment/meshi-api meshi-api=bamboooo/meshi-api:$GITHUB_SHA

      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.ORG_ROOTS_KUBE_CONFIG }}
          version: v1.21.2
          command: rollout status deployment/meshi-api
