// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Restaurant is the predicate function for restaurant builders.
type Restaurant func(*sql.Selector)
